In [1]:
pip install ipykernel

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

arr = np.array([10, 20, 30, 40])
print(arr)

[10 20 30 40]


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr + 5)

[6 7 8 9]


In [1]:
import numpy as np

arr = np.array([10,20,30])

print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(type(arr))

60
20.0
30
10
<class 'numpy.ndarray'>


In [2]:
matrix = np.array([[1,2],[3,4]])
print(matrix)

[[1 2]
 [3 4]]


In [3]:
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
print(np.ones((1,3)))

[[1. 1. 1.]]


In [6]:
arr = np.array([5,10,15,20,25])
print(arr[2])
print(arr[-1])


15
25


In [7]:
matrix = np.array([[10,20],[30,40]])
print(matrix[1][0])
print(arr[1:4])

30
[10 15 20]


In [8]:
arr = np.arange(12)
print(arr.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [12]:
arr = np.array([1,2,3,4])
print(arr+5)
print(arr*10)
print(np.sqrt(a))

[6 7 8 9]
[10 20 30 40]
[1.         1.41421356 1.73205081]


In [13]:
marks = np.array([70,85,60,90,75])

print("Mean:",marks.mean())
print("Max:",marks.max())
print("Min:",marks.min())
print("Sum:",marks.sum())

Mean: 76.0
Max: 90
Min: 60
Sum: 380


In [14]:
print(np.random.randint(1,100,10))
print(np.random.rand(5))

[ 2  1 37 14 14 18 49 38 55 60]
[0.56168953 0.91550976 0.60159581 0.41487438 0.8000532 ]
